# Generated by Django 6.0.5 on 2026-05-18 23:22

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('ingredientes', models.TextField()),
                ('pasos', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre', unique=True)),
                ('tiempo', models.CharField(max_length=100, null=True)),
                ('foto', models.CharField(max_length=200, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.categoria')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'db_table': 'recetas',
            },
        ),
    ]
